### ISSUE TITLE
Metadata licensing for PATHS corpora

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/paths-longtexts-dev#1]
Paths text documents and datasets are licensed CC BY-NC-SA 4.0.  We will need to license their text corpora under this license.  @amir-zeldes do you see any problem with this or have any thoughts before we go in and add/change the licensing in our corpora?  

I don't think we need to worry too much about licensing _other_ corpora with basic metadata from PATHS like dating of manuscripts when that info also exists elsewhere (e.g., print catalogs).

**Comment by ctschroeder** [comment]
Source: Paths, CMCL

Project: Paths, Scriptorium

**Comment by ctschroeder** [comment]
source_info either paths website link or paths github repo link or both

**Comment by amir-zeldes** [comment]
I would advocate website over github in this case, we don't know how stable those repos are

**Comment by amir-zeldes** [comment]
CC-BY-NC-SA should be fine, and of course we don't really have a choice, unless we ask them to change it. It makes me less eager to treebank them though - the more open the stuff there is, the better.

I agree publicly available metadata does not change the license of other datasets in this respect.

**Comment by lancealanmartin** [comment]
I changed the license for life.phib. Let me know if it is correct, and I will change the license for the other PATHS texts.

I amended the source and linked paths's website in source_info for all PATHS material.
